name: Bug report
description: Report a problem you encountered
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to complete this bug report!
        Please [search](https://github.com/Appsilon/shiny.fluent/issues)
        through existing issues first to make sure you are not creating a duplicate.

  - type: textarea
    attributes:
      label: Steps to reproduce
      value: '1. '
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug description
      description: What happened? Attach error messages and screenshots if applicable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comments
      description: Add any other useful information here.
