name: Bug report
description: Report a problem you encountered
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to complete this bug report!
        Please [search](https://github.com/Appsilon/shiny.fluent/issues)
        through existing issues first to make sure you are not creating a duplicate.

  - type: textarea
    attributes:
      label: Code example
      description: |
        Please provide a code example of the bug you're encountering.
        A good code example should meet the following criteria:

        1. **Minimal**: Only include the essential code needed to illustrate the problem.
        Remove any extraneous code that isn't directly related to the issue at hand.
        2. **Complete**: Include everything that someone else would need to run the example,
        such as the full contents of the app.R file.
        3. **Reproducible**: Ensure that the problem actually appears in the example.
        Include information like the R and package version, operating system, and browser.
        4. **Readable**: Use individual [Markdown code blocks](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code) for each file or code snippet.
        Use proper indentation, comments, and descriptive names.

        Check out [Reprex do's and don'ts](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) for even more great tips.
        Providing a good code example is crucial for us to reproduce and understand the bug.
        It increases the likelihood of addressing the issue quickly and effectively.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug description
      description: What happened? Attach error messages and screenshots if applicable.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What should have happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Comments
      description: Add any other useful information here.
