#' Reads a theme JSON generated by Theme Designer: \url{https://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/theming-designer/}
#' and parses it to an object digestable by \code{ThemeProvider}
#' @noRd
readTheme <- function(theme) {
  if (!file.exists(theme)) stop("Theme file doesn't exist.")
  palette <- jsonlite::read_json(theme)
  list(
    palette = palette
  )
}
